
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;


public class TwinCalc extends javax.swing.JFrame {

    /**
     * Creates new form TwinCalc
     */
    ImageIcon icon;
    public TwinCalc() {
        this.icon = new ImageIcon("src/icon1.png");
        initComponents();
    }
    
    /*播放普通音效：操作符*/
    public void playMusic()
{
	try {
		FileInputStream fileau=new FileInputStream("src/click.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
    /*播放等号音效*/
     public void playMusic2()
{
	try {
		FileInputStream fileau=new FileInputStream("src/ok.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
     /*toChange、toLeft音效*/
      public void playMusic3()
{
	try {
		FileInputStream fileau=new FileInputStream("src/change.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
     /*这里是溢出错误音效！！！！！*/
      public void playMusic4()
{
	try {
		FileInputStream fileau=new FileInputStream("src/error.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
public void one()
{
	try {
		FileInputStream fileau=new FileInputStream("src/one.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
public void two()
{
	try {
		FileInputStream fileau=new FileInputStream("src/two.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
public void three()
{
	try {
		FileInputStream fileau=new FileInputStream("src/three.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
public void four()
{
	try {
		FileInputStream fileau=new FileInputStream("src/four.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
 public void five()
{
	try {
		FileInputStream fileau=new FileInputStream("src/five.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
 public void six()
{
	try {
		FileInputStream fileau=new FileInputStream("src/six.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
     public void seven()
{
	try {
		FileInputStream fileau=new FileInputStream("src/seven.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
    public void eight()
{
	try {
		FileInputStream fileau=new FileInputStream("src/eight.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
  public void nine()
{
	try {
		FileInputStream fileau=new FileInputStream("src/nine.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
}
   public void zero()
{
	try {
		FileInputStream fileau=new FileInputStream("src/zero.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
} 
      public void clear()
{
	try {
		FileInputStream fileau=new FileInputStream("src/clear.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
} 
public void point()
{
	try {
		FileInputStream fileau=new FileInputStream("src/point.wav" );
		AudioStream as=new AudioStream(fileau);
		AudioPlayer.player.start(as);
	}catch (Exception e){
		e.printStackTrace();
	}
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ari1 = new javax.swing.JTextField();
        ari2 = new javax.swing.JTextField();
        ac1 = new javax.swing.JButton();
        seven1 = new javax.swing.JButton();
        four1 = new javax.swing.JButton();
        one1 = new javax.swing.JButton();
        zero1 = new javax.swing.JButton();
        change1 = new javax.swing.JButton();
        eight1 = new javax.swing.JButton();
        two1 = new javax.swing.JButton();
        five1 = new javax.swing.JButton();
        zero2 = new javax.swing.JButton();
        per1 = new javax.swing.JButton();
        nine1 = new javax.swing.JButton();
        six1 = new javax.swing.JButton();
        three1 = new javax.swing.JButton();
        point1 = new javax.swing.JButton();
        div1 = new javax.swing.JButton();
        mul1 = new javax.swing.JButton();
        sub1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        equ1 = new javax.swing.JButton();
        toRight = new javax.swing.JButton();
        toLeft = new javax.swing.JButton();
        del1 = new javax.swing.JButton();
        ac2 = new javax.swing.JButton();
        change2 = new javax.swing.JButton();
        seven2 = new javax.swing.JButton();
        nine2 = new javax.swing.JButton();
        per2 = new javax.swing.JButton();
        div2 = new javax.swing.JButton();
        mul2 = new javax.swing.JButton();
        five2 = new javax.swing.JButton();
        three2 = new javax.swing.JButton();
        sub2 = new javax.swing.JButton();
        point2 = new javax.swing.JButton();
        four2 = new javax.swing.JButton();
        six2 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        eight2 = new javax.swing.JButton();
        one2 = new javax.swing.JButton();
        two2 = new javax.swing.JButton();
        equ2 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        back2 = new javax.swing.JButton();
        result2 = new javax.swing.JTextField();
        result1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Twin-Calc");
        setIconImage(icon.getImage());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 576));

        ari1.setBackground(new java.awt.Color(0, 0, 0));
        ari1.setFont(new java.awt.Font("Yu Gothic", 1, 25)); // NOI18N
        ari1.setForeground(new java.awt.Color(255, 255, 255));
        ari1.setName("ar11"); // NOI18N
        ari1.setSelectionColor(new java.awt.Color(255, 255, 255));

        ari2.setBackground(new java.awt.Color(0, 0, 0));
        ari2.setFont(new java.awt.Font("Yu Gothic", 1, 25)); // NOI18N
        ari2.setForeground(new java.awt.Color(255, 255, 255));
        ari2.setCaretColor(new java.awt.Color(255, 255, 255));

        ac1.setBackground(new java.awt.Color(153, 153, 153));
        ac1.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        ac1.setForeground(new java.awt.Color(255, 255, 255));
        ac1.setText("AC");
        ac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac1ActionPerformed(evt);
            }
        });

        seven1.setBackground(new java.awt.Color(51, 51, 51));
        seven1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        seven1.setForeground(new java.awt.Color(255, 255, 255));
        seven1.setText("7");
        seven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven1ActionPerformed(evt);
            }
        });

        four1.setBackground(new java.awt.Color(51, 51, 51));
        four1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        four1.setForeground(new java.awt.Color(255, 255, 255));
        four1.setText("4");
        four1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four1ActionPerformed(evt);
            }
        });

        one1.setBackground(new java.awt.Color(51, 51, 51));
        one1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        one1.setForeground(new java.awt.Color(255, 255, 255));
        one1.setText("1");
        one1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one1ActionPerformed(evt);
            }
        });

        zero1.setBackground(new java.awt.Color(51, 51, 51));
        zero1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        zero1.setForeground(new java.awt.Color(255, 255, 255));
        zero1.setText("0");
        zero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero1ActionPerformed(evt);
            }
        });

        change1.setBackground(new java.awt.Color(153, 153, 153));
        change1.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        change1.setForeground(new java.awt.Color(255, 255, 255));
        change1.setText("+/-");
        change1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change1ActionPerformed(evt);
            }
        });

        eight1.setBackground(new java.awt.Color(51, 51, 51));
        eight1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        eight1.setForeground(new java.awt.Color(255, 255, 255));
        eight1.setText("8");
        eight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight1ActionPerformed(evt);
            }
        });

        two1.setBackground(new java.awt.Color(51, 51, 51));
        two1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        two1.setForeground(new java.awt.Color(255, 255, 255));
        two1.setText("2");
        two1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two1ActionPerformed(evt);
            }
        });

        five1.setBackground(new java.awt.Color(51, 51, 51));
        five1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        five1.setForeground(new java.awt.Color(255, 255, 255));
        five1.setText("5");
        five1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five1ActionPerformed(evt);
            }
        });

        zero2.setBackground(new java.awt.Color(51, 51, 51));
        zero2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        zero2.setForeground(new java.awt.Color(255, 255, 255));
        zero2.setText("0");
        zero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero2ActionPerformed(evt);
            }
        });

        per1.setBackground(new java.awt.Color(153, 153, 153));
        per1.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        per1.setForeground(new java.awt.Color(255, 255, 255));
        per1.setText("%");
        per1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                per1ActionPerformed(evt);
            }
        });

        nine1.setBackground(new java.awt.Color(51, 51, 51));
        nine1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        nine1.setForeground(new java.awt.Color(255, 255, 255));
        nine1.setText("9");
        nine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine1ActionPerformed(evt);
            }
        });

        six1.setBackground(new java.awt.Color(51, 51, 51));
        six1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        six1.setForeground(new java.awt.Color(255, 255, 255));
        six1.setText("6");
        six1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six1ActionPerformed(evt);
            }
        });

        three1.setBackground(new java.awt.Color(51, 51, 51));
        three1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        three1.setForeground(new java.awt.Color(255, 255, 255));
        three1.setText("3");
        three1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three1ActionPerformed(evt);
            }
        });

        point1.setBackground(new java.awt.Color(51, 51, 51));
        point1.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        point1.setForeground(new java.awt.Color(255, 255, 255));
        point1.setText(".");
        point1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1ActionPerformed(evt);
            }
        });

        div1.setBackground(new java.awt.Color(247, 190, 12));
        div1.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        div1.setForeground(new java.awt.Color(255, 255, 255));
        div1.setText("÷");
        div1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div1ActionPerformed(evt);
            }
        });

        mul1.setBackground(new java.awt.Color(244, 186, 12));
        mul1.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        mul1.setForeground(new java.awt.Color(255, 255, 255));
        mul1.setText("X");
        mul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul1ActionPerformed(evt);
            }
        });

        sub1.setBackground(new java.awt.Color(244, 186, 12));
        sub1.setFont(new java.awt.Font("Yu Gothic UI", 1, 45)); // NOI18N
        sub1.setForeground(new java.awt.Color(255, 255, 255));
        sub1.setText("-");
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        add1.setBackground(new java.awt.Color(244, 186, 12));
        add1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        add1.setForeground(new java.awt.Color(255, 255, 255));
        add1.setText("+");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        equ1.setBackground(new java.awt.Color(244, 186, 12));
        equ1.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        equ1.setForeground(new java.awt.Color(255, 255, 255));
        equ1.setText("=");
        equ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equ1ActionPerformed(evt);
            }
        });

        toRight.setBackground(new java.awt.Color(0, 153, 51));
        toRight.setFont(new java.awt.Font("Yu Gothic", 1, 38)); // NOI18N
        toRight.setForeground(new java.awt.Color(255, 255, 255));
        toRight.setText("⇨");
        toRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRightActionPerformed(evt);
            }
        });

        toLeft.setBackground(new java.awt.Color(0, 153, 51));
        toLeft.setFont(new java.awt.Font("Yu Gothic", 1, 38)); // NOI18N
        toLeft.setForeground(new java.awt.Color(255, 255, 255));
        toLeft.setText("⇦");
        toLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLeftActionPerformed(evt);
            }
        });

        del1.setBackground(new java.awt.Color(153, 153, 153));
        del1.setFont(new java.awt.Font("微软雅黑", 1, 20)); // NOI18N
        del1.setForeground(new java.awt.Color(255, 255, 255));
        del1.setText("DEL");
        del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del1ActionPerformed(evt);
            }
        });

        ac2.setBackground(new java.awt.Color(153, 153, 153));
        ac2.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        ac2.setForeground(new java.awt.Color(255, 255, 255));
        ac2.setText("AC");
        ac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac2ActionPerformed(evt);
            }
        });

        change2.setBackground(new java.awt.Color(153, 153, 153));
        change2.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        change2.setForeground(new java.awt.Color(255, 255, 255));
        change2.setText("+/-");
        change2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change2ActionPerformed(evt);
            }
        });

        seven2.setBackground(new java.awt.Color(51, 51, 51));
        seven2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        seven2.setForeground(new java.awt.Color(255, 255, 255));
        seven2.setText("7");
        seven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven2ActionPerformed(evt);
            }
        });

        nine2.setBackground(new java.awt.Color(51, 51, 51));
        nine2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        nine2.setForeground(new java.awt.Color(255, 255, 255));
        nine2.setText("9");
        nine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine2ActionPerformed(evt);
            }
        });

        per2.setBackground(new java.awt.Color(153, 153, 153));
        per2.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        per2.setForeground(new java.awt.Color(255, 255, 255));
        per2.setText("%");
        per2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                per2ActionPerformed(evt);
            }
        });

        div2.setBackground(new java.awt.Color(244, 186, 12));
        div2.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        div2.setForeground(new java.awt.Color(255, 255, 255));
        div2.setText("÷");
        div2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div2ActionPerformed(evt);
            }
        });

        mul2.setBackground(new java.awt.Color(244, 186, 12));
        mul2.setFont(new java.awt.Font("Yu Gothic", 1, 35)); // NOI18N
        mul2.setForeground(new java.awt.Color(255, 255, 255));
        mul2.setText("X");
        mul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul2ActionPerformed(evt);
            }
        });

        five2.setBackground(new java.awt.Color(51, 51, 51));
        five2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        five2.setForeground(new java.awt.Color(255, 255, 255));
        five2.setText("5");
        five2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five2ActionPerformed(evt);
            }
        });

        three2.setBackground(new java.awt.Color(51, 51, 51));
        three2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        three2.setForeground(new java.awt.Color(255, 255, 255));
        three2.setText("3");
        three2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three2ActionPerformed(evt);
            }
        });

        sub2.setBackground(new java.awt.Color(244, 186, 12));
        sub2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        sub2.setForeground(new java.awt.Color(255, 255, 255));
        sub2.setText("-");
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });

        point2.setBackground(new java.awt.Color(51, 51, 51));
        point2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        point2.setForeground(new java.awt.Color(255, 255, 255));
        point2.setText(".");
        point2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2ActionPerformed(evt);
            }
        });

        four2.setBackground(new java.awt.Color(51, 51, 51));
        four2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        four2.setForeground(new java.awt.Color(255, 255, 255));
        four2.setText("4");
        four2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four2ActionPerformed(evt);
            }
        });

        six2.setBackground(new java.awt.Color(51, 51, 51));
        six2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        six2.setForeground(new java.awt.Color(255, 255, 255));
        six2.setText("6");
        six2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six2ActionPerformed(evt);
            }
        });

        add2.setBackground(new java.awt.Color(244, 186, 12));
        add2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        add2.setForeground(new java.awt.Color(255, 255, 255));
        add2.setText("+");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        eight2.setBackground(new java.awt.Color(51, 51, 51));
        eight2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        eight2.setForeground(new java.awt.Color(255, 255, 255));
        eight2.setText("8");
        eight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight2ActionPerformed(evt);
            }
        });

        one2.setBackground(new java.awt.Color(51, 51, 51));
        one2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        one2.setForeground(new java.awt.Color(255, 255, 255));
        one2.setText("1");
        one2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one2ActionPerformed(evt);
            }
        });

        two2.setBackground(new java.awt.Color(51, 51, 51));
        two2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        two2.setForeground(new java.awt.Color(255, 255, 255));
        two2.setText("2");
        two2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two2ActionPerformed(evt);
            }
        });

        equ2.setBackground(new java.awt.Color(244, 186, 12));
        equ2.setFont(new java.awt.Font("Yu Gothic", 1, 45)); // NOI18N
        equ2.setForeground(new java.awt.Color(255, 255, 255));
        equ2.setText("=");
        equ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equ2ActionPerformed(evt);
            }
        });

        back1.setBackground(new java.awt.Color(51, 51, 51));
        back1.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("BACK");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        back2.setBackground(new java.awt.Color(51, 51, 51));
        back2.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        back2.setForeground(new java.awt.Color(255, 255, 255));
        back2.setText("BACK");
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });

        result2.setBackground(new java.awt.Color(0, 0, 0));
        result2.setFont(new java.awt.Font("Yu Gothic", 1, 50)); // NOI18N
        result2.setForeground(new java.awt.Color(255, 255, 255));
        result2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        result1.setBackground(new java.awt.Color(0, 0, 0));
        result1.setFont(new java.awt.Font("Yu Gothic", 1, 50)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));
        result1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(two1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(three1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(three2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(eight1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(nine1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(mul1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(toRight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(eight2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(nine2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(mul2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(five1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(six1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(five2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(six2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(zero1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(point1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(equ1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(del1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(zero2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(point2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(equ2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ac1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(change1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(per1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(div1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(toLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ac2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(change2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(per2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(div2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ari1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(ari2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ari1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ari2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(div1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(per1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ac1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(change2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(per2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toRight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(four2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(del1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equ1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equ2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void one1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one1ActionPerformed
        // TODO add your handling code here:
         one();
    }//GEN-LAST:event_one1ActionPerformed

    private void nine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine1ActionPerformed
        // TODO add your handling code here:
         nine();
    }//GEN-LAST:event_nine1ActionPerformed

    private void ac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac1ActionPerformed
        // TODO add your handling code here:
        playMusic();
    }//GEN-LAST:event_ac1ActionPerformed

    private void per2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_per2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_per2ActionPerformed

    private void ac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac2ActionPerformed
        // TODO add your handling code here:
        playMusic();
    }//GEN-LAST:event_ac2ActionPerformed

    private void one2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one2ActionPerformed
        // TODO add your handling code here:
           one();
    }//GEN-LAST:event_one2ActionPerformed

    private void two2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two2ActionPerformed
        // TODO add your handling code here:
           two();
    }//GEN-LAST:event_two2ActionPerformed

    private void toLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLeftActionPerformed
        // TODO add your handling code here:
        playMusic3();
    }//GEN-LAST:event_toLeftActionPerformed

    private void change1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change1ActionPerformed
        // TODO add your handling code here:
        playMusic();
    }//GEN-LAST:event_change1ActionPerformed

    private void per1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_per1ActionPerformed
        // TODO add your handling code here:
        playMusic();
    }//GEN-LAST:event_per1ActionPerformed

    private void div1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div1ActionPerformed
        // TODO add your handling code here:
         playMusic();
    }//GEN-LAST:event_div1ActionPerformed

    private void seven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven1ActionPerformed
        // TODO add your handling code here:
         seven();
    }//GEN-LAST:event_seven1ActionPerformed

    private void eight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight1ActionPerformed
        // TODO add your handling code here:
         eight();
    }//GEN-LAST:event_eight1ActionPerformed

    private void mul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul1ActionPerformed
        // TODO add your handling code here:
         playMusic();
    }//GEN-LAST:event_mul1ActionPerformed

    private void four1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four1ActionPerformed
        // TODO add your handling code here:
         four();
    }//GEN-LAST:event_four1ActionPerformed

    private void five1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five1ActionPerformed
        // TODO add your handling code here:
         five();
    }//GEN-LAST:event_five1ActionPerformed

    private void six1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six1ActionPerformed
        // TODO add your handling code here:
         six();
    }//GEN-LAST:event_six1ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
         playMusic();
    }//GEN-LAST:event_sub1ActionPerformed

    private void two1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two1ActionPerformed
        // TODO add your handling code here:
         two();
    }//GEN-LAST:event_two1ActionPerformed

    private void three1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three1ActionPerformed
        // TODO add your handling code here:
         three();
    }//GEN-LAST:event_three1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
         playMusic();
    }//GEN-LAST:event_add1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
         playMusic();
    }//GEN-LAST:event_back1ActionPerformed

    private void zero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero1ActionPerformed
        // TODO add your handling code here:
         zero();
    }//GEN-LAST:event_zero1ActionPerformed

    private void point1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1ActionPerformed
        // TODO add your handling code here:
         point();
    }//GEN-LAST:event_point1ActionPerformed

    private void equ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equ1ActionPerformed
        // TODO add your handling code here:
         playMusic2();
    }//GEN-LAST:event_equ1ActionPerformed

    private void toRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRightActionPerformed
        // TODO add your handling code here:
        playMusic3();
    }//GEN-LAST:event_toRightActionPerformed

    private void del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_del1ActionPerformed

    private void change2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change2ActionPerformed
        // TODO add your handling code here:
        playMusic();
    }//GEN-LAST:event_change2ActionPerformed

    private void div2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_div2ActionPerformed

    private void seven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven2ActionPerformed
        // TODO add your handling code here:
           seven();
    }//GEN-LAST:event_seven2ActionPerformed

    private void eight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight2ActionPerformed
        // TODO add your handling code here:
           eight();
    }//GEN-LAST:event_eight2ActionPerformed

    private void nine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine2ActionPerformed
        // TODO add your handling code here:
           nine();
    }//GEN-LAST:event_nine2ActionPerformed

    private void mul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_mul2ActionPerformed

    private void four2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four2ActionPerformed
        // TODO add your handling code here:
           four();
    }//GEN-LAST:event_four2ActionPerformed

    private void five2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five2ActionPerformed
        // TODO add your handling code here:
           five();
    }//GEN-LAST:event_five2ActionPerformed

    private void six2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six2ActionPerformed
        // TODO add your handling code here:
           six();
    }//GEN-LAST:event_six2ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_sub2ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_add2ActionPerformed

    private void three2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three2ActionPerformed
        // TODO add your handling code here:
           three();
    }//GEN-LAST:event_three2ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        // TODO add your handling code here:
           playMusic();
    }//GEN-LAST:event_back2ActionPerformed

    private void zero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero2ActionPerformed
        // TODO add your handling code here:
           zero();
    }//GEN-LAST:event_zero2ActionPerformed

    private void point2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2ActionPerformed
        // TODO add your handling code here:
           point();
    }//GEN-LAST:event_point2ActionPerformed

    private void equ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equ2ActionPerformed
        // TODO add your handling code here:
           playMusic2();
    }//GEN-LAST:event_equ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwinCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwinCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwinCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwinCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwinCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ac1;
    private javax.swing.JButton ac2;
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JTextField ari1;
    private javax.swing.JTextField ari2;
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JButton change1;
    private javax.swing.JButton change2;
    private javax.swing.JButton del1;
    private javax.swing.JButton div1;
    private javax.swing.JButton div2;
    private javax.swing.JButton eight1;
    private javax.swing.JButton eight2;
    private javax.swing.JButton equ1;
    private javax.swing.JButton equ2;
    private javax.swing.JButton five1;
    private javax.swing.JButton five2;
    private javax.swing.JButton four1;
    private javax.swing.JButton four2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mul1;
    private javax.swing.JButton mul2;
    private javax.swing.JButton nine1;
    private javax.swing.JButton nine2;
    private javax.swing.JButton one1;
    private javax.swing.JButton one2;
    private javax.swing.JButton per1;
    private javax.swing.JButton per2;
    private javax.swing.JButton point1;
    private javax.swing.JButton point2;
    private javax.swing.JTextField result1;
    private javax.swing.JTextField result2;
    private javax.swing.JButton seven1;
    private javax.swing.JButton seven2;
    private javax.swing.JButton six1;
    private javax.swing.JButton six2;
    private javax.swing.JButton sub1;
    private javax.swing.JButton sub2;
    private javax.swing.JButton three1;
    private javax.swing.JButton three2;
    private javax.swing.JButton toLeft;
    private javax.swing.JButton toRight;
    private javax.swing.JButton two1;
    private javax.swing.JButton two2;
    private javax.swing.JButton zero1;
    private javax.swing.JButton zero2;
    // End of variables declaration//GEN-END:variables
}
